# Default values for grafana-plugin-installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Grafana options
grafana:
  # Name of existing PersistentVolumeClaim
  pvcName: grafana-pvc
  dataDir: "/var/lib/grafana"
  runAsUser: 472
  runAsGroup: 472

# Plugin options
plugin:
  name: "devopsprodigy-kubegraf-app"
  repo: "https://github.com/devopsprodigy/kubegraf.git"
  # plugin version to install
  tag: master
