apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "grafana-plugin-installer.name" . }}-config"
  labels:
    app: "{{ include "grafana-plugin-installer.name" . }}"
data:
  main.sh: |
    #!/bin/sh
    if [ ! -d $GRAFANA_PLUGIN_DIR ] ; then
      git clone --branch {{ .Values.plugin.tag }} {{ .Values.plugin.repo }} $GRAFANA_PLUGIN_DIR
    else
      git -C $GRAFANA_PLUGIN_DIR fetch
      git -C $GRAFANA_PLUGIN_DIR checkout {{ .Values.plugin.tag }}
    fi
