apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "grafana-plugin-installer.name" . }}-{{ .Values.plugin.tag }}"
  labels:
    app: "{{ include "grafana-plugin-installer.name" . }}"
    tag: "{{ .Values.plugin.tag }}"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: installer
        image: devopsprodigy/grafana-plugin-installer:0.0.1
        securityContext:
          runAsUser: {{ .Values.grafana.runAsUser }}
          runAsGroup: {{ .Values.grafana.runAsGroup }}
        volumeMounts:
        - mountPath: "{{ .Values.grafana.dataDir }}"
          name: storage
        env:
        - name: GRAFANA_PLUGIN_DIR
          value: "{{ .Values.grafana.dataDir }}/plugins/{{ .Values.plugin.name }}"
        - name: GRAFANA_PLUGIN_REPO
          value: "{{ .Values.plugin.repo }}"
        - name: GRAFANA_PLUGIN_TAG
          value: "{{ .Values.plugin.tag }}"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.grafana.pvcName }}
